name: cypher-api

services:
  cypher-database:
    image: postgres:15-alpine
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - cypher-postgres:/var/lib/postgresql/data

  livekit-server:
    build:
      context: .
      dockerfile: services/livekit/Dockerfile # Path to your Dockerfile
    ports:
      - 7880:7880
    command: ['livekit-server', '--dev', '--bind', '0.0.0.0']

volumes:
  cypher-postgres:
