export const API_ACCESS_TOKEN_EXPIRES_IN_MINUTES = 2;
export const API_ACCESS_TOKEN_EXPIRES_IN_MILLISECONDS =
  API_ACCESS_TOKEN_EXPIRES_IN_MINUTES * 60 * 1000;
export const FRONT_ACCESS_TOKEN_REFETCH_INTERVAL_IN_SECONDS =
  (API_ACCESS_TOKEN_EXPIRES_IN_MINUTES / 2) * 60;
export const API_ACCESS_TOKEN_REVALIDATE_INTERVAL_IN_MILLISECONDS =
  FRONT_ACCESS_TOKEN_REFETCH_INTERVAL_IN_SECONDS * 1000;
export const FRONT_ACCESS_TOKEN_EXPIRES_IN_SECONDS = 7 * 24 * 60 * 60;
