export const metadata = {
  title: 'Welcome to front',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ background: 'black', color: 'white' }}>
      <body>{children}</body>
    </html>
  );
}
