name: cypher-api

services:
  cypher-database:
    image: postgres:15-alpine
    env_file:
      - ../../.env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - cypher-postgres:/var/lib/postgresql/data

volumes:
  cypher-postgres:
